
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:

  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/WeatherCompanyDataTests/Credentials.swift.enc -out Tests/WeatherCompanyDataTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/AlchemyVisionTests/Credentials.swift.enc -out Tests/AlchemyVisionTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/NaturalLanguageClassifierTests/Credentials.swift.enc -out Tests/NaturalLanguageClassifierTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/ToneAnalyzerTests/Credentials.swift.enc -out Tests/ToneAnalyzerTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/PersonalityInsightsTests/Credentials.swift.enc -out Tests/PersonalityInsightsTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/ConversationTests/Credentials.swift.enc -out Tests/ConversationTests/Credentials.swift -d
  - openssl aes-256-cbc -K $encrypted_26ed6ae22807_key -iv $encrypted_26ed6ae22807_iv -in Tests/AlchemyLanguageTests/Credentials.swift.enc -out Tests/AlchemyLanguageTests/Credentials.swift -d

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install http-parser curl  ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-3.0-RELEASE-ubuntu14.04/usr/bin:$PATH    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang-3.8 ; fi
  
script:
  - swift build
  - swift test
